pipeline {
    agent any

    stages{
        stage("checkout") {
        steps {
            checkout scm
        }
    }

        stage("Terraform init") {
            steps {
                sh  {"terraform init -reconfigure"}
            }
        }

        stage("plan") {
            steps {
                sh "terraform plan"
    }
}
        stage("Action") {
            steps {
                echo "Terraform action is --> ${action}"
                sh {"terraform ${action} --auto-approve"}
            }
        }
}
}