pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages{
        stage("checkout") {
        steps {
            checkout scm
        }
    }

        stage("Terraform init") {
            steps {
                sh  {"terraform init -reconfigure"}
            }
        }

        stage("plan") {
            steps {
                sh "terraform plan"
    }
}
        stage("Action") {
            steps {
                echo "Terraform action is --> ${action}"
                sh {"terraform ${action} --auto-approve"}
            }
        }
}
}